shell: zsh
region: us-east-1
dotfiles: https://github.com/k-phan/dd-dotfiles
vscode-extensions:
- "anysphere.cursorpyright"
- "charliermarsh.ruff"
- "dbaeumer.vscode-eslint"
- "eamodio.gitlens"
- "editorconfig.editorconfig"
- "esbenp.prettier-vscode"
- "golang.go"
- "hashicorp.terraform"
- "ms-kubernetes-tools.vscode-kubernetes-tools"
- "ms-python.black-formatter"
- "ms-python.debugpy"
- "ms-python.isort"
- "ms-python.python"
- "ms-python.vscode-pylance"
- "redhat.vscode-yaml"
- "stackbuild.bazel-stack-vscode"
- "streetsidesoftware.code-spell-checker"
- "stylelint.vscode-stylelint"
- "zxh404.vscode-proto3"
vscode-template: "dd-source"